import { MedicalDomain } from "./MedicalIntelligenceLayer";

export const MEDICAL_CAPABILITIES: MedicalDomain[] = [
  "ANATOMY",
  "PHYSIOLOGY",
  "PATHOLOGY",
  "PHARMACOLOGY",
  "MICROBIOLOGY",
  "IMMUNOLOGY",
  "GENETICS",
  "EPIDEMIOLOGY",
  "DIAGNOSTICS",
  "IMAGING",
  "LABORATORY",
  "PREVENTION",
  "PUBLIC_HEALTH",
  "CLINICAL_RESEARCH",
  "MEDICAL_DOCUMENTATION",
  "PATIENT_EDUCATION",
  "TRIAGE",
  "CLINICAL_DECISION_SUPPORT",
];
