import { TechnicalDomain } from "./UniversalTechnicalOperations";

export const TECHNICAL_DOMAINS: TechnicalDomain[] = [
  "SOFTWARE",
  "HARDWARE",
  "IT",
  "NETWORKING",
  "CLOUD",
  "DEVOPS",
  "DATABASE",
  "AI_ML",
  "DATA",
  "CYBERSECURITY",
  "ELECTRONICS",
  "EMBEDDED",
  "AUTOMATION",
  "ROBOTICS",
  "SYSTEMS",
  "ENGINEERING_TOOLS",
  "TESTING",
  "DEBUGGING",
  "PERFORMANCE",
  "UI_UX",
  "MEDIA_TECHNOLOGY",
  "API_INTEGRATION",
  "DOCUMENTATION",
  "MONITORING",
  "RECOVERY",
];
