export type QualityLifecycleStage =
  | "PLAN"
  | "REQUIREMENTS"
  | "RISK_ASSESSMENT"
  | "DESIGN"
  | "INSTALLATION"
  | "COMMISSIONING"
  | "QUALIFICATION"
  | "VALIDATION"
  | "APPROVAL"
  | "TRAINING"
  | "OPERATION"
  | "MONITORING"
  | "DEVIATION"
  | "INVESTIGATION"
  | "CAPA"
  | "CHANGE_CONTROL"
  | "PERIODIC_REVIEW"
  | "RETIREMENT";

export const QUALITY_LIFECYCLE: QualityLifecycleStage[] = [
  "PLAN",
  "REQUIREMENTS",
  "RISK_ASSESSMENT",
  "DESIGN",
  "INSTALLATION",
  "COMMISSIONING",
  "QUALIFICATION",
  "VALIDATION",
  "APPROVAL",
  "TRAINING",
  "OPERATION",
  "MONITORING",
  "DEVIATION",
  "INVESTIGATION",
  "CAPA",
  "CHANGE_CONTROL",
  "PERIODIC_REVIEW",
  "RETIREMENT",
];
